routes/web.php
<?php

// App\User::create([
// 	'name' => 'Osmin',
// 	'email' => 'martinezmonjaras2015@gmail.com',
// 	'password' => bcrypt('123123'),
// 	'role_id' => 2
// ]);

// DB::listen(function($query) {
// 	echo "<pre>{$query->sql}</pre>";
// });

// Route::get('job', function() {
// 	dispatch(new App\Jobs\SendEmail);

// 	return "Listo";
// });

Route::get('roles', function() {
	return \App\Role::with('users')->get();
});

Route::get('/', ['as' => 'home', 'uses' => 'PagesController@home']);

Route::get('saludos/{nombre?}', ['as' => 'saludos', 'uses' => 'PagesController@saludo'])->where('nombre', '[A-Za-z]+');

Route::resource('mensajes', 'MessagesController');
Route::resource('usuarios', 'UsersController');

Route::get('login', ['as' => 'login', 'uses' => 'Auth\LoginController@showLoginForm']);
Route::post('login', 'Auth\LoginController@login');
Route::get('logout', 'Auth\LoginController@logout');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use App\Presenters\UserPresenter;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'avatar',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function setPasswordAttribute($password) {
        $this->attributes['password'] = bcrypt($password);
    }

    public function roles() {
        return $this->belongsToMany(Role::class, 'assigned_roles');
    }


    public function hasRoles(array $roles) {
        return $this->roles->pluck('name')->intersect($roles)->count();
    }

    public function isAdmin() {
        return $this->hasRoles(['admin']);
    }

    public function messages() {
        return $this->hasMany(Message::class);
    }

    public function note() {
        return $this->morphOne(Note::class, 'notable');
    }

    public function tags() {
        return $this->morphToMany(Tag::class, 'taggable')->withTimestamps();
    }

    public function present() 
    {
        return new UserPresenter($this);
    }
}

app/Http/Controllers/UsersController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\User;
use App\Role;
use App\Http\Requests\UpdateUserRequest;
use App\Http\Requests\CreateUserRequest;

class UsersController extends Controller
{
    public function __construct() 
    {
        $this->middleware('auth', ['except' => ['show']]);
        $this->middleware('roles:admin', ['except' => ['edit', 'update', 'show']]);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::with(['roles', 'note', 'tags'])->get();
        return view('users.index', compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $roles = Role::pluck('display_name', 'id');

        return view('users.create', compact('roles'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Requests\CreateUserRequest $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateUserRequest $request)
    {

        $user = (new User)->fill($request->all());

        $user->avatar = $request->file('avatar')->store('public');

        $user->save();

        $user->roles()->attach($request->roles);

        return redirect()->route('usuarios.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $user = User::findOrFail($id);

        return view('users.show', compact('user'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = User::findOrFail($id);

        $this->authorize('edit', $user);

        $roles = Role::pluck('display_name', 'id');

        return view('users.edit', compact('user', 'roles'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateUserRequest $request, $id)
    {

        $user = User::findOrFail($id);

        $this->authorize('update', $user);

        if ($request->hasFile('avatar'))
        {
            $user->avatar = $request->file('avatar')->store('public');
        }

        $user->update($request->only('name', 'email'));

        $user->roles()->sync($request->roles);

        return back()->with('info', 'Usuario actualizado');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user = User::findOrFail($id);

        $this->authorize('destroy', $user);

        $user->delete();

        return back();
    }
}

resources/views/users/create.blade.php
@extends('layout')

@section('contenido')
	
	<h1>Crear nuevo usuario</h1>

	<form method="POST" 
		action="{{ route('usuarios.store') }}"
		enctype="multipart/form-data">
		
		@include('users.form', ['user' => new App\User])	

		<input type="submit" value="Guardar" class="btn btn-primary">
	</form>

@stop

resources/views/users/edit.blade.php
@extends('layout')

@section('contenido')
	
	<h1>Editar Usuario</h1>
	
	@if(session()->has('info'))
		<div class="alert alert-success">{{ session('info') }}</div>
	@endif

	<form method="POST" 
			action="{{ route('usuarios.update', $user->id) }}"
			enctype="multipart/form-data">
		{{ method_field('PUT') }}

		<img width="100px" src="{{ Storage::url($user->avatar) }}">
		 
		@include('users.form')	

		<input type="submit" value="Editar" class="btn btn-primary">
	</form>

@stop

resources/views/users/form.blade.php
{{csrf_field()}}

<p><label for="avatar">
	<input type="file" name="avatar" class="form-control">
	{!! $errors->first('avatar', '<span class="error">:message</span>') !!}
</label></p>

<p><label for="name">
	Nombre
	<input type="text" name="name" value="{{ $user->name or old('name')}}" class="form-control">
	{!! $errors->first('name', '<span class="error">:message</span>') !!}
</label></p>

<p><label for="email">
	Email
	<input type="text" name="email" value="{{ $user->email or old('email')}}" class="form-control">
	{!! $errors->first('email', '<span class="error">:message</span>') !!}
</label></p>

@unless($user->id)
	
	<p><label for="password">
		Password
		<input type="password" name="password" class="form-control">
		{!! $errors->first('password', '<span class="error">:message</span>') !!}
	</label></p>

	<p><label for="password_confirmation">
		Password Confirm
		<input type="password" name="password_confirmation" class="form-control">
		{!! $errors->first('password_confirmation', '<span class="error">:message</span>') !!}
	</label></p>
	
@endunless

<div class="checkbox">
	@foreach($roles as $id => $name) 
		<label>
			<input 
				type="checkbox" 
				value="{{ $id }}" 
				name="roles[]"
				{{ $user->roles->pluck('id')->contains($id) ? 'checked' : '' }}
				>
			{{$name}}
		</label>
	@endforeach
</div>
{!! $errors->first('roles', '<span class="error">:message</span>') !!}
<hr>

resources/views/users/index.blade.php
@extends('layout')

@section('contenido')
	
	<h1>Todos los mensajes</h1>
	
	<a class="btn btn-primary pull-right" href="{{ route('usuarios.create') }}">Crear nuevo usuario</a>

	<table class="table">
		<thead>
			<tr>
				<td>ID</td>
				<td>Nombre</td>
				<td>Email</td>
				<td>Role</td>
				<td>Notas</td>
				<td>Etiquetas</td>
				<th>Acciones</th>
			</tr>
		</thead>
		<tbody>
			@foreach($users as $user)
				<tr>
					<td>{{ $user->id }}</td>
					<td>{{ $user->present()->link() }}</td>
					<td>{{ $user->email }}</td>
					<td>{{ $user->present()->roles() }}</td>
					<td>{{ $user->present()->notes() }}</td>
					<td>{{ $user->present()->tags() }}</td>
					<td>
						<a class="btn btn-info btn-xs" 
							href="{{ route('usuarios.edit', $user->id) }}">Editar</a>
						<form style="display: inline;" 
							method="POST" 
							action="{{ route('usuarios.destroy', $user->id) }}">
							{{ csrf_field() }}
							{{ method_field('DELETE') }}
							<button class="btn btn-danger btn-xs" type="submit">Eliminar</button>
						</form>
					</td>
				</tr>
			@endforeach
		</tbody>
	</table>
@stop

resources/views/users/show.blade.php
@extends('layout')

@section('contenido')
	
	<img width="100px" src="{{ Storage::url($user->avatar) }}">

	<h1>{{ $user->name }}</h1>
	<table class="table">
		<tr>
			<th>Nombre:</th>
			<td>{{ $user->name }}</td>
		</tr>
		<tr>
			<th>Email:</th>
			<td>{{ $user->email }}</td>
		</tr>
		<tr>
			<th>Roles:</th>
			<td>@foreach($user->roles as $role)
				{{ $role->display_name }}
			@endforeach</td>
		</tr>
	</table>

	@can('edit', $user) 
		<a href="{{ route('usuarios.edit', $user->id) }}" class="btn btn-info">Editar</a>
	@endcan

	@can('destroy', $user) 
		<form style="display: inline;"
			method="POST"
			action="{{ route('usuarios.destroy', $user->id) }}">
			
			{{ csrf_field() }}
			{{ method_field('DELETE') }}

			<button class="btn btn-danger">Eliminar</button>		
		</form>
	@endcan
@stop