routes/web.php
<?php

// App\User::create([
// 	'name' => 'Osmin',
// 	'email' => 'martinezmonjaras2015@gmail.com',
// 	'password' => bcrypt('123123'),
// 	'role_id' => 2
// ]);

// DB::listen(function($query) {
// 	echo "<pre>{$query->sql}</pre>";
// });

// Route::get('job', function() {
// 	dispatch(new App\Jobs\SendEmail);

// 	return "Listo";
// });

Route::get('roles', function() {
	return \App\Role::with('users')->get();
});

Route::get('/', ['as' => 'home', 'uses' => 'PagesController@home']);

Route::get('saludos/{nombre?}', ['as' => 'saludos', 'uses' => 'PagesController@saludo'])->where('nombre', '[A-Za-z]+');

Route::resource('mensajes', 'MessagesController');
Route::resource('usuarios', 'UsersController');

Route::get('login', ['as' => 'login', 'uses' => 'Auth\LoginController@showLoginForm']);
Route::post('login', 'Auth\LoginController@login');
Route::get('logout', 'Auth\LoginController@logout');

app/Message.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Presenters\MessagePresenter;

class Message extends Model
{
    //
    protected $fillable = ["nombre", "email", "mensaje"];

    public function user()
    {
    	return $this->belongsTo(User::class);
    }

    public function note() {
    	return $this->morphOne(Note::class, 'notable');
    }

    public function tags() {
    	return $this->morphToMany(Tag::class, 'taggable');
    }

    public function present() 
    {
        return new MessagePresenter($this);
    }
}

app/Http/Controllers/MessagesController.php
<?php

namespace App\Http\Controllers;

use Mail;
use App\Message;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Routing\Redirector;
use App\Mail\TuMensajeFueRecibido;
use App\Events\MessageWasReceived;
use App\Repositories\MessagesInterface;
use Illuminate\Events\Dispatcher as Event;
use Illuminate\Contracts\View\Factory as ViewFactory;


class MessagesController extends Controller
{

    protected $messages;
    protected $view;
    protected $redirect;

    function __construct(MessagesInterface $messages, ViewFactory $view, Redirector $redirect ) 
    {
        $this->view = $view;
        $this->messages = $messages;
        $this->redirect = $redirect;
        $this->middleware('auth', ['except' => ['create', 'store']]);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $messages = $this->messages->getPaginated();

        return $this->view->make('messages.index', ['messages' => $messages]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return $this->view->make('messages.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request, Event $event)
    {
        $message = $this->messages->store($request);

        $event->fire(new MessageWasReceived($message));
        
        // //Redireccionar
        return $this->redirect->route('mensajes.create')
            ->with('info', 'Hemos recibido tu mensaje')
        ;
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        
        $message = $this->messages->findById($id);
 
        return $this->view->make("messages.show", compact('message'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $message = $this->messages->findById($id);

        return $this->view->make('messages.edit', compact('message'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        
        $message = $this->messages->update($request, $id);

        //Redireccionar
        return $this->redirect->route('mensajes.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $this->messages->destroy($id);

        return $this->redirect->route('mensajes.index');
    }
}

resources/views/messages/create.blade.php
@extends('layout')

@section('contenido')
	<h1>Contactos</h1>

	<h2>Escribeme</h2>
	
	@if( session()->has('info') )
		<h3>{{ session('info') }}</h3>
	@else

	<form method="POST" action="{{ route('mensajes.store') }}">
		@include('messages.form', [
			'message' => new App\Message,
			'showFields' => auth()->guest()
		])
	</form>

	@endif
@stop

resources/views/messages/edit.blade.php
@extends('layout')

@section('contenido')

	<h1>Editar mensaje</h1>
	
	<form method="POST" action="{{ route('mensajes.update', $message->id) }}">
		{{ method_field('PUT') }}
		@include('messages.form', [
			'btnText' => 'Actualizar',
			'showFields' => ! $message->user_id
		])
	</form>
@stop

resources/views/messages/form.blade.php
{{csrf_field()}}
@if($showFields)

	<p><label for="nombre">
		Nombre
		<input class="form-control" type="text" name="nombre" value="{{ $message->nombre or  old('nombre') }}">
		{!! $errors->first('nombre', '<span class="error">:message</span>') !!}
	</label></p>

	<p><label for="email">
		Email
		<input class="form-control" type="text" name="email" value="{{ $message->email or  old('email') }}">
		{!! $errors->first('email', '<span class="error">:message</span>') !!}
	</label></p>

@endif

<p><label for="mensaje">
	Mensaje
	<textarea class="form-control" name="mensaje">{{ $message->mensaje or old('mensaje') }}</textarea>
	{!! $errors->first('mensaje', '<span class="error">:message</span>') !!}
</label></p>

<input class="btn btn-primary" type="submit" value="{{  $btnText or 'Guardar' }}">

resources/views/messages/index.blade.php
@extends('layout')

@section('contenido')
	
	<h1>Todos los mensajes</h1>

	<table class="table">
		<thead>
			<tr>
				<td>ID</td>
				<td>Nombre</td>
				<td>Email</td>
				<td>Mensaje</td>
				<td>Notas</td>
				<td>Etiquetas</td>
				<td>Acciones</td>
			</tr>
		</thead>
		<tbody>
			@foreach($messages as $message)
			<tr>
				<td>{{ $message->id }}</td>
				<td>{{ $message->present()->userName() }}</td>
				<td>{{ $message->present()->userEmail() }}</td>
				<td>{{ $message->present()->link() }}</td>
				<td>{{ $message->present()->notes() }}</td>
				<td>{{ $message->present()->tags() }}</td>
				<td>
					<a class="btn btn-info btn-xs" href="{{ route('mensajes.edit', $message->id) }}">Editar</a>
					<form style="display: inline;" method="POST" action="{{ route('mensajes.destroy', $message->id) }}">
						{{ csrf_field() }}
						{{ method_field('DELETE') }}
						<button class="btn btn-danger btn-xs" type="submit">Eliminar</button>
					</form>
				</td>
			</tr>
			@endforeach

			{{ $messages->fragment('hash')->appends(request()->query())->links('pagination::simple-default') }}
		</tbody>
	</table>
@stop

resources/views/messages/show.blade.php
@extends('layout')

@section('contenido')

	<h1>Mensaje</h1>
	
	<p>Enviado por {{ $message->present()->userName() }} - {{ $message->present()->userEmail() }}</p>

	<p>Hola soy {{ $message->mensaje }}</p>
@stop